#!/usr/bin/env bash

# Change working directory to the top-most Finder window location
function cdf() { # short for `cdfinder`
	cd "$(osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)')";
}

# Create a data URL from a file
function dataurl() {
	local mimeType=$(file -b --mime-type "$1");
	if [[ $mimeType == text/* ]]; then
		mimeType="${mimeType};charset=utf-8";
	fi
	echo "data:${mimeType};base64,$(openssl base64 -in "$1" | tr -d '\n')";
}

# open dict.cc dictionary
dcc () {
	open "https://www.dict.cc/?s=${(j:+:)@}"
}

# fetch gitignore.io suggestions for given type
gi () {
	curl -fLw '\n' "https://www.gitignore.io/api/${(j:,:)@}"
}

# Check if main exists and use instead of master
git_main_branch() {
  command git rev-parse --git-dir &>/dev/null || return
  local ref
  for ref in refs/{heads,remotes/{origin,upstream}}/{main,trunk}; do
    if command git show-ref -q --verify $ref; then
      echo ${ref:t}
      return
    fi
  done
  echo master
}

# search with google
google(){
  open "https://www.google.com/search?q=${(j:+:)@}"
}

# Create a new directory and enter it
function mkd() {
	mkdir -p "$@" && cd "$_";
}
